In [1]:
import pandas as pd

# Read the CSV and Preform Basic Data Cleaning

In [2]:
gender_df = pd.read_csv("data/gender_submission.csv")
test_df = pd.read_csv("data/test.csv")
train_df = pd.read_csv("data/train.csv")

In [3]:
train_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
test_df.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [5]:
gender_df

PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [6]:
# Use the following fields in the model 
#  Pclass, Sex, age, SibSp, Parch, fare 

# training set: remove all columns that are not needed
# testing set: remove all columns that are not needed

# verify that the 'mix' of the training and test set are similar 

# X_train - train.csv - split the survived into y_train 
# X_test - test.csv 
# y_train - target - survived from the train.csv 
# y_test - gender file 


# may need to clean up NaN and make sure the coresponding y value is removed also 
# X_train[X_train['Age'].isnull()]
# either drop 'Age' 
#  or imputing data - add a median age (by male and female)


# Scale: Pclass, Age, SibSp, Parch, Fare 
# Encode: Sex



In [7]:
X_train = train_df[['Pclass', 'Sex', 'Survived','Age', 'SibSp', 'Parch', 'Fare']]

In [8]:
X_train = X_train.dropna()

In [9]:
X_train

Pclass     Sex  Survived   Age  SibSp  Parch     Fare
0         3    male         0  22.0      1      0   7.2500
1         1  female         1  38.0      1      0  71.2833
2         3  female         1  26.0      0      0   7.9250
3         1  female         1  35.0      1      0  53.1000
4         3    male         0  35.0      0      0   8.0500
..      ...     ...       ...   ...    ...    ...      ...
885       3  female         0  39.0      0      5  29.1250
886       2    male         0  27.0      0      0  13.0000
887       1  female         1  19.0      0      0  30.0000
889       1    male         1  26.0      0      0  30.0000
890       3    male         0  32.0      0      0   7.7500

[714 rows x 7 columns]

In [10]:
y_train = X_train[['Survived']]

In [11]:
y_train = y_train.values.reshape(-1, 1)

In [12]:
y_train

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [13]:
X_train = X_train[['Pclass', 'Sex','Age', 'SibSp', 'Parch', 'Fare']]

In [14]:
X_train

Pclass     Sex   Age  SibSp  Parch     Fare
0         3    male  22.0      1      0   7.2500
1         1  female  38.0      1      0  71.2833
2         3  female  26.0      0      0   7.9250
3         1  female  35.0      1      0  53.1000
4         3    male  35.0      0      0   8.0500
..      ...     ...   ...    ...    ...      ...
885       3  female  39.0      0      5  29.1250
886       2    male  27.0      0      0  13.0000
887       1  female  19.0      0      0  30.0000
889       1    male  26.0      0      0  30.0000
890       3    male  32.0      0      0   7.7500

[714 rows x 6 columns]

In [15]:
# merge gender_df and test_df
merged_df = test_df.merge(gender_df, on='PassengerId')

In [16]:
merged_df  

PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  \
0      male  34.5      0      0              330911    7.8292   NaN        Q   
1    female  47.0      1      0              363272    7.0000   NaN        S   
2      male  62.0      0      0              240276    9.6875   NaN        Q   
3      male  27.0      0      0              315154    8.6625   NaN        S   
4    female  22.0      1      1             3101298   12.2875   NaN        S   
..      ...   ...    ...    ...                 ...       ...   ...      ...   
413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S   
414  female  39.0      0      0            PC 17758  108.9000  C105        C   
415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S   
416    male   NaN      0      0              359309    8.0500   NaN        S   
417    male   NaN      1      1                2668   22.3583   NaN        C   

     Survived  
0           0  
1           1  
2           0  
3           0  
4           1  
..        ...  
413         0  
414         1  
415         0  
416         0  
417         0  

[418 rows x 12 columns]

In [17]:
merged_df = merged_df[['Pclass', 'Sex', 'Survived','Age', 'SibSp', 'Parch', 'Fare']]

In [18]:
merged_df

Pclass     Sex  Survived   Age  SibSp  Parch      Fare
0         3    male         0  34.5      0      0    7.8292
1         3  female         1  47.0      1      0    7.0000
2         2    male         0  62.0      0      0    9.6875
3         3    male         0  27.0      0      0    8.6625
4         3  female         1  22.0      1      1   12.2875
..      ...     ...       ...   ...    ...    ...       ...
413       3    male         0   NaN      0      0    8.0500
414       1  female         1  39.0      0      0  108.9000
415       3    male         0  38.5      0      0    7.2500
416       3    male         0   NaN      0      0    8.0500
417       3    male         0   NaN      1      1   22.3583

[418 rows x 7 columns]

In [19]:
merged_df.dropna()

Pclass     Sex  Survived   Age  SibSp  Parch      Fare
0         3    male         0  34.5      0      0    7.8292
1         3  female         1  47.0      1      0    7.0000
2         2    male         0  62.0      0      0    9.6875
3         3    male         0  27.0      0      0    8.6625
4         3  female         1  22.0      1      1   12.2875
..      ...     ...       ...   ...    ...    ...       ...
409       3  female         1   3.0      1      1   13.7750
411       1  female         1  37.0      1      0   90.0000
412       3  female         1  28.0      0      0    7.7750
414       1  female         1  39.0      0      0  108.9000
415       3    male         0  38.5      0      0    7.2500

[331 rows x 7 columns]

In [20]:
X_test = merged_df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']]

In [21]:
X_test

Pclass     Sex   Age  SibSp  Parch      Fare
0         3    male  34.5      0      0    7.8292
1         3  female  47.0      1      0    7.0000
2         2    male  62.0      0      0    9.6875
3         3    male  27.0      0      0    8.6625
4         3  female  22.0      1      1   12.2875
..      ...     ...   ...    ...    ...       ...
413       3    male   NaN      0      0    8.0500
414       1  female  39.0      0      0  108.9000
415       3    male  38.5      0      0    7.2500
416       3    male   NaN      0      0    8.0500
417       3    male   NaN      1      1   22.3583

[418 rows x 6 columns]

In [22]:
y_test = merged_df[['Survived']]

In [23]:
y_test = y_test.values.reshape(-1, 1)

#y = smoking["FEV"].values.reshape(-1, 1)

In [24]:
y_test

array([[0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
    

In [25]:

X_test = X_test.copy()

X_test = pd.get_dummies(X_test, columns=["Sex"])
X_test.head()


Pclass   Age  SibSp  Parch     Fare  Sex_female  Sex_male
0       3  34.5      0      0   7.8292           0         1
1       3  47.0      1      0   7.0000           1         0
2       2  62.0      0      0   9.6875           0         1
3       3  27.0      0      0   8.6625           0         1
4       3  22.0      1      1  12.2875           1         0

In [26]:

X_train = X_train.copy()

X_train = pd.get_dummies(X_train, columns=["Sex"])
X_train.head()

Pclass   Age  SibSp  Parch     Fare  Sex_female  Sex_male
0       3  22.0      1      0   7.2500           0         1
1       1  38.0      1      0  71.2833           1         0
2       3  26.0      0      0   7.9250           1         0
3       1  35.0      1      0  53.1000           1         0
4       3  35.0      0      0   8.0500           0         1

In [27]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)
y_scaler = StandardScaler().fit(y_train)

In [28]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
y_train_scaled = y_scaler.transform(y_train)
y_test_scaled = y_scaler.transform(y_test)

In [29]:
X_test_scaled

array([[ 0.91123237,  0.33072307, -0.55170307, ..., -0.50802515,
        -0.75905134,  0.75905134],
       [ 0.91123237,  1.19182279,  0.52457013, ..., -0.52370538,
         1.31743394, -1.31743394],
       [-0.28256564,  2.22514245, -0.55170307, ..., -0.47288455,
        -0.75905134,  0.75905134],
       ...,
       [ 0.91123237,  0.60627498, -0.55170307, ..., -0.51897787,
        -0.75905134,  0.75905134],
       [ 0.91123237,         nan, -0.55170307, ..., -0.5038498 ,
        -0.75905134,  0.75905134],
       [ 0.91123237,         nan,  0.52457013, ..., -0.23327875,
        -0.75905134,  0.75905134]])

In [30]:
X_test_scaled

array([[ 0.91123237,  0.33072307, -0.55170307, ..., -0.50802515,
        -0.75905134,  0.75905134],
       [ 0.91123237,  1.19182279,  0.52457013, ..., -0.52370538,
         1.31743394, -1.31743394],
       [-0.28256564,  2.22514245, -0.55170307, ..., -0.47288455,
        -0.75905134,  0.75905134],
       ...,
       [ 0.91123237,  0.60627498, -0.55170307, ..., -0.51897787,
        -0.75905134,  0.75905134],
       [ 0.91123237,         nan, -0.55170307, ..., -0.5038498 ,
        -0.75905134,  0.75905134],
       [ 0.91123237,         nan,  0.52457013, ..., -0.23327875,
        -0.75905134,  0.75905134]])

In [31]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(max_iter=1000)
classifier

LogisticRegression(max_iter=1000)

In [32]:
classifier.fit(X_train, y_train)

/opt/anaconda3/envs/PythonData38/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(max_iter=1000)